module SharedVariables
  @senators_list = {
    "Kenneth P. LaValle" => {party: "Republican", conference: "Republican", district: "1", id: "4518711"},
    "John J. Flanagan" => {party: "Republican", conference: "Republican", district: "2", id: "4518701"},
    "Thomas Croci" => {party: "Republican", conference: "Republican", district: "3", id: "4518811"},
    "Philip M. Boyle" => {party: "Republican", conference: "Republican", district: "4", id: "4518836"},
    "Carl L. Marcellino" => {party: "Republican", conference: "Republican", district: "5", id: "4518666"},
    "Kemp Hannon" => {party: "Republican", conference: "Republican", district: "6", id: "4518706"},
    "Elaine Phillips" => {party: "Republican", conference: "Republican", district: "7", id: "6253904"},
    "John Brooks" => {party: "Democratic", conference: "Democratic", district: "8", id: "6254384"},
    "Todd Kaminsky" => {party: "Democratic", conference: "Democratic", district: "9", id: "6204631"},
    "James Sanders, Jr." => {party: "Democratic", conference: "Democratic", district: "10", id: "4518841"},
    "Tony Avella" => {party: "Democratic", conference: "IDC", district: "11", id: "4518821"},
    "Michael N. Gianaris" => {party: "Democratic", conference: "Democratic", district: "12", id: "4518811"},
    "Jose Peralta" => {party: "Democratic", conference: "IDC", district: "13", id: "4518756"},
    "Leroy Comrie" => {party: "Democratic", conference: "Democratic", district: "14", id: "4518911"},
    "Joseph P. Addabbo, Jr." => {party: "Democratic", conference: "Democratic", district: "15", id: "4518476"},
    "Toby Ann Stavisky" => {party: "Democratic", conference: "Democratic", district: "16", id: "4518481"},
    "Simcha Felder" => {party: "Democratic", conference: "Republican", district: "17", id: "4518846"},
    "Martin Malave Dilan" => {party: "Democratic", conference: "Democratic", district: "18", id: "4518486"},
    "Roxane Persaud" => {party: "Democratic", conference: "Democratic", district: "19", id: "6191151"},
    "Jesse Hamilton" => {party: "Democratic", conference: "IDC", district: "20", id: "4518916"},
    "Kevin S. Parker" => {party: "Democratic", conference: "Democratic", district: "21", id: "4518506"},
    "Martin J. Golden" => {party: "Republican", conference: "Republican", district: "22", id: "4518716"},
    "Diane Savino" => {party: "Democratic", conference: "IDC", district: "23", id: "4518511"},
    "Andrew J. Lanza" => {party: "Republican", conference: "Republican", district: "24", id: "4518661"},
    "Velmanette Montgomery" => {party: "Democratic", conference: "Democratic", district: "25", id: "4518491"},
    "Brian Kavanagh" => {party: "Democratic", conference: "Democratic", district: "26", id: "6397156"},
    "Brad Hoylman" => {party: "Democratic", conference: "Democratic", district: "27", id: "4518851"},
    "Liz Krueger" => {party: "Democratic", conference: "Democratic", district: "28", id: "4518521"},
    "Jose M. Serrano" => {party: "Democratic", conference: "Democratic", district: "29", id: "4518531"},
    "Brian Benjamin" => {party: "Democratic", conference: "Democratic", district: "30", id: "6288051"},
    "Marisol Alcantara" => {party: "Democratic", conference: "IDC", district: "31", id: "6253906"},
    "Gustavo Rivera" => {party: "Democratic", conference: "Democratic", district: "33", id: "4518806"},
    "Jeffrey D. Klein" => {party: "Democratic", conference: "IDC", district: "34", id: "4518571"},
    "Andrea Stewart-Cousins" => {party: "Democratic", conference: "Democratic", district: "35", id: "4518551"},
    "Jamaal Bailey" => {party: "Democratic", conference: "Democratic", district: "36", id: "6253905"},
    "David Carlucci" => {party: "Democratic", conference: "IDC", district: "38", id: "4518801"},
    "William J. Larkin, Jr." => {party: "Republican", conference: "Republican", district: "39", id: "4518746"},
    "Terrence P. Murphy" => {party: "Republican", conference: "Republican", district: "40", id: "4518891"},
    "Susan J. Serino" => {party: "Republican", conference: "Republican", district: "41", id: "4518896"},
    "John J. Bonacic" => {party: "Republican", conference: "Republican", district: "42", id: "4518656"},
    "Kathleen A. Marchione" => {party: "Republican", conference: "Republican", district: "43", id: "4518861"},
    "Neil Breslin" => {party: "Democratic", conference: "Democratic", district: "44", id: "4518596"},
    "Betty Little" => {party: "Republican", conference: "Republican", district: "45", id: "4518651"},
    "George A. Amedore, Jr." => {party: "Republican", conference: "Republican", district: "46", id: "4518876"},
    "Joseph Griffo" => {party: "Republican", conference: "Republican", district: "47", id: "4518646"},
    "Patty Ritchie" => {party: "Republican", conference: "Republican", district: "48", id: "4518776"},
    "Jim Tedisco" => {party: "Republican", conference: "Republican", district: "49", id: "6253898"},
    "John DeFrancisco" => {party: "Republican", conference: "Republican", district: "50", id: "4518641"},
    "James Seward" => {party: "Republican", conference: "Republican", district: "51", id: "4518636"},
    "Fred Akshar" => {party: "Republican", conference: "Republican", district: "52", id: "6187911"},
    "David Valesky" => {party: "Democratic", conference: "IDC", district: "53", id: "4518616"},
    "Pam Helming" => {party: "Republican", conference: "Republican", district: "54", id: "6253901"},
    "Rich Funke" => {party: "Republican", conference: "Republican", district: "55", id: "4518901"},
    "Joseph Robach" => {party: "Republican", conference: "Republican", district: "56", id: "4518581"},
    "Catharine Young" => {party: "Republican", conference: "Republican", district: "57", id: "4518576"},
    "Tom O'Mara" => {party: "Republican", conference: "Republican", district: "58", id: "4518781"},
    "Patrick Gallivan" => {party: "Republican", conference: "Republican", district: "59", id: "4518786"},
    "Chris Jacobs" => {party: "Republican", conference: "Republican", district: "60", id: "6253903"},
    "Michael H. Ranzenhofer" => {party: "Republican", conference: "Republican", district: "61", id: "4518721"},
    "Robert G. Ortt" => {party: "Republican", conference: "Republican", district: "62", id: "4518906"},
    "Timothy M. Kennedy" => {party: "Democratic", conference: "Democratic", district: "63", id: "4518816"}
  }

  @assembly_list = {
    "THIELE"=>{:party=>"Independence", :district=>"1", :fullname=>"Fred Thiele"},
    "PALUMBO"=>{:party=>"Republican", :district=>"2", :fullname=>"Anthony Palumbo"},
    "MURRAY"=>{:party=>"Republican", :district=>"3", :fullname=>"L. Dean Murray"},
    "ENGLEBRIGHT"=>{:party=>"Democratic", :district=>"4", :fullname=>"Steven Englebright"},
    "RAMOS"=>{:party=>"Democratic", :district=>"6", :fullname=>"Philip Ramos"},
    "GARBARINO"=>{:party=>"Republican", :district=>"7", :fullname=>"Andrew Garbarino"},
    "FITZPATRICK"=>{:party=>"Republican", :district=>"8", :fullname=>"Michael J. Fitzpatrick"},
    "PELLEGRINO"=>{:party=>"Democratic", :district=>"9", :fullname=>"Christine Pellegrino"},
    "JEAN-PIERRE"=>{:party=>"Democratic", :district=>"11", :fullname=>"Kimberly Jean-Pierre"},
    "RAIA"=>{:party=>"Republican", :district=>"12", :fullname=>"Andrew Raia"},
    "LAVINE"=>{:party=>"Democratic", :district=>"13", :fullname=>"Charles Lavine"},
    "MCDONOUGH"=>{:party=>"Republican", :district=>"14", :fullname=>"David McDonough"},
    "MONTESANO"=>{:party=>"Republican", :district=>"15", :fullname=>"Michael Montesano"},
    "D'URSO"=>{:party=>"Democratic", :district=>"16", :fullname=>"Anthony D'Urso"},
    "HOOPER"=>{:party=>"Democratic", :district=>"18", :fullname=>"Earlene Hooper"},
    "RA"=>{:party=>"Republican", :district=>"19", :fullname=>"Ed Ra"},
    "MILLER ML"=>{:party=>"Republican", :district=>"20", :fullname=>"Melissa Miller"},
    "CURRAN"=>{:party=>"Republican", :district=>"21", :fullname=>"Brian F. Curran"},
    "SOLAGES"=>{:party=>"Democratic", :district=>"22", :fullname=>"Michaelle C. Solages"},
    "PHEFFER AMATO"=>{:party=>"Democratic", :district=>"23", :fullname=>"Stacey Pheffer Amato"},
    "WEPRIN"=>{:party=>"Democratic", :district=>"24", :fullname=>"David Weprin"},
    "ROZIC"=>{:party=>"Democratic", :district=>"25", :fullname=>"Nily Rozic"},
    "BRAUNSTEIN"=>{:party=>"Democratic", :district=>"26", :fullname=>"Edward Braunstein"},
    "ROSENTHAL D"=>{:party=>"Democratic", :district=>"27", :fullname=>"Daniel Rosenthal"},
    "HEVESI"=>{:party=>"Democratic", :district=>"28", :fullname=>"Andrew Hevesi"},
    "HYNDMAN"=>{:party=>"Democratic", :district=>"29", :fullname=>"Alicia Hyndman"},
    "BARNWELL"=>{:party=>"Democratic", :district=>"30", :fullname=>"Brian Barnwell"},
    "TITUS"=>{:party=>"Democratic", :district=>"31", :fullname=>"Michele Titus"},
    "COOK"=>{:party=>"Democratic", :district=>"32", :fullname=>"Vivian Cook"},
    "VANEL"=>{:party=>"Democratic", :district=>"33", :fullname=>"Clyde Vanel"},
    "DENDEKKER"=>{:party=>"Democratic", :district=>"34", :fullname=>"Michael DenDekker"},
    "AUBRY"=>{:party=>"Democratic", :district=>"35", :fullname=>"Jeffrion Aubry"},
    "SIMOTAS"=>{:party=>"Democratic", :district=>"36", :fullname=>"Aravella Simotas"},
    "NOLAN"=>{:party=>"Democratic", :district=>"37", :fullname=>"Catherine Nolan"},
    "MILLER MG"=>{:party=>"Democratic", :district=>"38", :fullname=>"Michael G. Miller"},
    "KIM"=>{:party=>"Democratic", :district=>"40", :fullname=>"Ron Kim"},
    "WEINSTEIN"=>{:party=>"Democratic", :district=>"41", :fullname=>"Helene Weinstein"},
    "BICHOTTE"=>{:party=>"Democratic", :district=>"42", :fullname=>"Rodneyse Bichotte"},
    "RICHARDSON"=>{:party=>"Democratic", :district=>"43", :fullname=>"Diana Richardson"},
    "CARROLL"=>{:party=>"Democratic", :district=>"44", :fullname=>"Robert Carroll"},
    "CYMBROWITZ"=>{:party=>"Democratic", :district=>"45", :fullname=>"Steven Cymbrowitz"},
    "HARRIS"=>{:party=>"Democratic", :district=>"46", :fullname=>"Pamela Harris"},
    "COLTON"=>{:party=>"Democratic", :district=>"47", :fullname=>"William Colton"},
    "HIKIND"=>{:party=>"Democratic", :district=>"48", :fullname=>"Dov Hikind"},
    "ABBATE"=>{:party=>"Democratic", :district=>"49", :fullname=>"Peter Abbate"},
    "LENTOL"=>{:party=>"Democratic", :district=>"50", :fullname=>"Joseph Lentol"},
    "ORTIZ"=>{:party=>"Democratic", :district=>"51", :fullname=>"Félix Ortiz"},
    "SIMON"=>{:party=>"Democratic", :district=>"52", :fullname=>"Jo Anne Simon"},
    "DAVILA"=>{:party=>"Democratic", :district=>"53", :fullname=>"Maritza Davila"},
    "DILAN"=>{:party=>"Democratic", :district=>"54", :fullname=>"Erik Dilan"},
    "WALKER"=>{:party=>"Democratic", :district=>"55", :fullname=>"Latrice Walker"},
    "WRIGHT"=>{:party=>"Democratic", :district=>"56", :fullname=>"Tremaine Wright"},
    "MOSLEY"=>{:party=>"Democratic", :district=>"57", :fullname=>"Walter T. Mosley"},
    "PERRY"=>{:party=>"Democratic", :district=>"58", :fullname=>"N. Nick Perry"},
    "WILLIAMS"=>{:party=>"Democratic", :district=>"59", :fullname=>"Jaime Williams"},
    "BARRON"=>{:party=>"Democratic", :district=>"60", :fullname=>"Charles Barron"},
    "TITONE"=>{:party=>"Democratic", :district=>"61", :fullname=>"Matthew Titone"},
    "CASTORINA"=>{:party=>"Republican", :district=>"62", :fullname=>"Ronald Castorina"},
    "CUSICK"=>{:party=>"Democratic", :district=>"63", :fullname=>"Michael Cusick"},
    "MALLIOTAKIS"=>{:party=>"Republican", :district=>"64", :fullname=>"Nicole Malliotakis"},
    "NIOU"=>{:party=>"Democratic", :district=>"65", :fullname=>"Yuh-Line Niou"},
    "GLICK"=>{:party=>"Democratic", :district=>"66", :fullname=>"Deborah Glick"},
    "ROSENTHAL L"=>{:party=>"Democratic", :district=>"67", :fullname=>"Linda Rosenthal"},
    "RODRIGUEZ"=>{:party=>"Democratic", :district=>"68", :fullname=>"Robert J. Rodriguez"},
    "O'DONNELL"=>{:party=>"Democratic", :district=>"69", :fullname=>"Daniel O'Donnell"},
    "DICKENS"=>{:party=>"Democratic", :district=>"70", :fullname=>"Inez Dickens"},
    "TAYLOR"=>{:party=>"Democratic", :district=>"71", :fullname=>"Al Taylor"},
    "DE LA ROSA"=>{:party=>"Democratic", :district=>"72", :fullname=>"Carmen De La Rosa"},
    "QUART"=>{:party=>"Democratic", :district=>"73", :fullname=>"Dan Quart"},
    "GOTTFRIED"=>{:party=>"Democratic", :district=>"75", :fullname=>"Richard Gottfried"},
    "SEAWRIGHT"=>{:party=>"Democratic", :district=>"76", :fullname=>"Rebecca Seawright"},
    "JOYNER"=>{:party=>"Democratic", :district=>"77", :fullname=>"Latoya Joyner"},
    "RIVERA"=>{:party=>"Democratic", :district=>"78", :fullname=>"Jose Rivera"},
    "BLAKE"=>{:party=>"Democratic", :district=>"79", :fullname=>"Michael Blake"},
    "DINOWITZ"=>{:party=>"Democratic", :district=>"81", :fullname=>"Jeffrey Dinowitz"},
    "BENEDETTO"=>{:party=>"Democratic", :district=>"82", :fullname=>"Michael Benedetto"},
    "HEASTIE"=>{:party=>"Democratic", :district=>"83", :fullname=>"Carl Heastie"},
    "ARROYO"=>{:party=>"Democratic", :district=>"84", :fullname=>"Carmen E. Arroyo"},
    "CRESPO"=>{:party=>"Democratic", :district=>"85", :fullname=>"Marcos Crespo"},
    "PICHARDO"=>{:party=>"Democratic", :district=>"86", :fullname=>"Victor M. Pichardo"},
    "SEPULVEDA"=>{:party=>"Democratic", :district=>"87", :fullname=>"Luis R. Sepúlveda"},
    "PAULIN"=>{:party=>"Democratic", :district=>"88", :fullname=>"Amy Paulin"},
    "PRETLOW"=>{:party=>"Democratic", :district=>"89", :fullname=>"J. Gary Pretlow"},
    "MAYER"=>{:party=>"Democratic", :district=>"90", :fullname=>"Shelley Mayer"},
    "OTIS"=>{:party=>"Democratic", :district=>"91", :fullname=>"Steven Otis"},
    "ABINANTI"=>{:party=>"Democratic", :district=>"92", :fullname=>"Tom Abinanti"},
    "BUCHWALD"=>{:party=>"Democratic", :district=>"93", :fullname=>"David Buchwald"},
    "BYRNE"=>{:party=>"Republican", :district=>"94", :fullname=>"Kevin Byrne"},
    "GALEF"=>{:party=>"Democratic", :district=>"95", :fullname=>"Sandy Galef"},
    "ZEBROWSKI"=>{:party=>"Democratic", :district=>"96", :fullname=>"Kenneth Zebrowski, Jr."},
    "JAFFEE"=>{:party=>"Democratic", :district=>"97", :fullname=>"Ellen Jaffee"},
    "BRABENEC"=>{:party=>"Republican", :district=>"98", :fullname=>"Karl A. Brabenec"},
    "SKOUFIS"=>{:party=>"Democratic", :district=>"99", :fullname=>"James Skoufis"},
    "GUNTHER"=>{:party=>"Democratic", :district=>"100", :fullname=>"Aileen Gunther"},
    "MILLER B"=>{:party=>"Republican", :district=>"101", :fullname=>"Brian Miller"},
    "CAHILL"=>{:party=>"Democratic", :district=>"103", :fullname=>"Kevin Cahill"},
    "SKARTADOS"=>{:party=>"Democratic", :district=>"104", :fullname=>"Frank Skartados"},
    "LALOR"=>{:party=>"Republican", :district=>"105", :fullname=>"Kieran Lalor"},
    "BARRETT"=>{:party=>"Democratic", :district=>"106", :fullname=>"Didi Barrett"},
    "MCDONALD"=>{:party=>"Democratic", :district=>"108", :fullname=>"John T. McDonald III"},
    "FAHY"=>{:party=>"Democratic", :district=>"109", :fullname=>"Patricia Fahy"},
    "STECK"=>{:party=>"Democratic", :district=>"110", :fullname=>"Phil Steck"},
    "SANTABARBARA"=>{:party=>"Democratic", :district=>"111", :fullname=>"Angelo Santabarbara"},
    "WALSH"=>{:party=>"Republican", :district=>"112", :fullname=>"Mary Beth Walsh"},
    "WOERNER"=>{:party=>"Democratic", :district=>"113", :fullname=>"Carrie Woerner"},
    "STEC"=>{:party=>"Republican", :district=>"114", :fullname=>"Dan Stec"},
    "JONES"=>{:party=>"Democratic", :district=>"115", :fullname=>"Billy Jones"},
    "JENNE"=>{:party=>"Democratic", :district=>"116", :fullname=>"Addie Jenne"},
    "BLANKENBUSH"=>{:party=>"Republican", :district=>"117", :fullname=>"Ken Blankenbush"},
    "BUTLER"=>{:party=>"Republican", :district=>"118", :fullname=>"Marc Butler"},
    "BRINDISI"=>{:party=>"Democratic", :district=>"119", :fullname=>"Anthony Brindisi"},
    "BARCLAY"=>{:party=>"Republican", :district=>"120", :fullname=>"William A. Barclay"},
    "MAGEE"=>{:party=>"Democratic", :district=>"121", :fullname=>"William Magee"},
    "CROUCH"=>{:party=>"Republican", :district=>"122", :fullname=>"Clifford Crouch"},
    "LUPARDO"=>{:party=>"Democratic", :district=>"123", :fullname=>"Donna Lupardo"},
    "FRIEND"=>{:party=>"Republican", :district=>"124", :fullname=>"Christopher Friend"},
    "LIFTON"=>{:party=>"Democratic", :district=>"125", :fullname=>"Barbara Lifton"},
    "FINCH"=>{:party=>"Republican", :district=>"126", :fullname=>"Gary Finch"},
    "STIRPE"=>{:party=>"Democratic", :district=>"127", :fullname=>"Al Stirpe"},
    "HUNTER"=>{:party=>"Democratic", :district=>"128", :fullname=>"Pamela Hunter"},
    "MAGNARELLI"=>{:party=>"Democratic", :district=>"129", :fullname=>"William Magnarelli"},
    "OAKS"=>{:party=>"Republican", :district=>"130", :fullname=>"Robert Oaks"},
    "KOLB"=>{:party=>"Republican", :district=>"131", :fullname=>"Brian Kolb"},
    "PALMESANO"=>{:party=>"Republican", :district=>"132", :fullname=>"Philip Palmesano"},
    "ERRIGO"=>{:party=>"Republican", :district=>"133", :fullname=>"Joseph Errigo"},
    "LAWRENCE"=>{:party=>"Republican", :district=>"134", :fullname=>"Peter Lawrence"},
    "JOHNS"=>{:party=>"Republican", :district=>"135", :fullname=>"Mark C. Johns"},
    "MORELLE"=>{:party=>"Democratic", :district=>"136", :fullname=>"Joseph Morelle"},
    "GANTT"=>{:party=>"Democratic", :district=>"137", :fullname=>"David Gantt"},
    "BRONSON"=>{:party=>"Democratic", :district=>"138", :fullname=>"Harry Bronson"},
    "HAWLEY"=>{:party=>"Republican", :district=>"139", :fullname=>"Stephen Hawley"},
    "SCHIMMINGER"=>{:party=>"Democratic", :district=>"140", :fullname=>"Robin Schimminger"},
    "PEOPLES-STOKES"=>{:party=>"Democratic", :district=>"141", :fullname=>"Crystal Peoples-Stokes"},
    "WALLACE"=>{:party=>"Democratic", :district=>"143", :fullname=>"Monica P. Wallace"},
    "NORRIS"=>{:party=>"Republican", :district=>"144", :fullname=>"Michael Norris"},
    "MORINELLO"=>{:party=>"Republican", :district=>"145", :fullname=>"Angelo Morinello"},
    "WALTER"=>{:party=>"Republican", :district=>"146", :fullname=>"Raymond Walter"},
    "DIPIETRO"=>{:party=>"Republican", :district=>"147", :fullname=>"David DiPietro"},
    "GIGLIO"=>{:party=>"Republican", :district=>"148", :fullname=>"Joseph Giglio"},
    "RYAN"=>{:party=>"Democratic", :district=>"149", :fullname=>"Sean Ryan"},
    "GOODELL"=>{:party=>"Republican", :district=>"150", :fullname=>"Andy Goodell"}
  }

  def self.senators_list
    return @senators_list
  end

  def self.assembly_list
    return @assembly_list
  end

end
