module SharedVariables
  @senators_list = {
    "Kenneth P. LaValle" => {party: "Republican", conference: "Republican", district: "1", id: "4518711"},
    "John J. Flanagan" => {party: "Republican", conference: "Republican", district: "2", id: "4518701"},
    "Thomas Croci" => {party: "Republican", conference: "Republican", district: "3", id: "4518811"},
    "Philip M. Boyle" => {party: "Republican", conference: "Republican", district: "4", id: "4518836"},
    "Carl L. Marcellino" => {party: "Republican", conference: "Republican", district: "5", id: "4518666"},
    "Kemp Hannon" => {party: "Republican", conference: "Republican", district: "6", id: "4518706"},
    "Elaine Phillips" => {party: "Republican", conference: "Republican", district: "7", id: "6253904"},
    "John Brooks" => {party: "Democratic", conference: "Democratic", district: "8", id: "6254384"},
    "Todd Kaminsky" => {party: "Democratic", conference: "Democratic", district: "9", id: "6204631"},
    "James Sanders, Jr." => {party: "Democratic", conference: "Democratic", district: "10", id: "4518841"},
    "Tony Avella" => {party: "Democratic", conference: "IDC", district: "11", id: "4518821"},
    "Michael N. Gianaris" => {party: "Democratic", conference: "Democratic", district: "12", id: "4518811"},
    "Jose Peralta" => {party: "Democratic", conference: "IDC", district: "13", id: "4518756"},
    "Leroy Comrie" => {party: "Democratic", conference: "Democratic", district: "14", id: "4518911"},
    "Joseph P. Addabbo, Jr." => {party: "Democratic", conference: "Democratic", district: "15", id: "4518476"},
    "Toby Ann Stavisky" => {party: "Democratic", conference: "Democratic", district: "16", id: "4518481"},
    "Simcha Felder" => {party: "Democratic", conference: "Republican", district: "17", id: "4518846"},
    "Martin Malave Dilan" => {party: "Democratic", conference: "Democratic", district: "18", id: "4518486"},
    "Roxane Persaud" => {party: "Democratic", conference: "Democratic", district: "19", id: "6191151"},
    "Jesse Hamilton" => {party: "Democratic", conference: "IDC", district: "20", id: "4518916"},
    "Kevin S. Parker" => {party: "Democratic", conference: "Democratic", district: "21", id: "4518506"},
    "Martin J. Golden" => {party: "Republican", conference: "Republican", district: "22", id: "4518716"},
    "Diane Savino" => {party: "Democratic", conference: "IDC", district: "23", id: "4518511"},
    "Andrew J. Lanza" => {party: "Republican", conference: "Republican", district: "24", id: "4518661"},
    "Velmanette Montgomery" => {party: "Democratic", conference: "Democratic", district: "25", id: "4518491"},
    "Brian Kavanagh" => {party: "Democratic", conference: "Democratic", district: "26", id: "6397156"},
    "Brad Hoylman" => {party: "Democratic", conference: "Democratic", district: "27", id: "4518851"},
    "Liz Krueger" => {party: "Democratic", conference: "Democratic", district: "28", id: "4518521"},
    "Jose M. Serrano" => {party: "Democratic", conference: "Democratic", district: "29", id: "4518531"},
    "Brian Benjamin" => {party: "Democratic", conference: "Democratic", district: "30", id: "6288051"},
    "Marisol Alcantara" => {party: "Democratic", conference: "IDC", district: "31", id: "6253906"},
    "Gustavo Rivera" => {party: "Democratic", conference: "Democratic", district: "33", id: "4518806"},
    "Jeffrey D. Klein" => {party: "Democratic", conference: "IDC", district: "34", id: "4518571"},
    "Andrea Stewart-Cousins" => {party: "Democratic", conference: "Democratic", district: "35", id: "4518551"},
    "Jamaal Bailey" => {party: "Democratic", conference: "Democratic", district: "36", id: "6253905"},
    "David Carlucci" => {party: "Democratic", conference: "IDC", district: "38", id: "4518801"},
    "William J. Larkin, Jr." => {party: "Republican", conference: "Republican", district: "39", id: "4518746"},
    "Terrence P. Murphy" => {party: "Republican", conference: "Republican", district: "40", id: "4518891"},
    "Susan J. Serino" => {party: "Republican", conference: "Republican", district: "41", id: "4518896"},
    "John J. Bonacic" => {party: "Republican", conference: "Republican", district: "42", id: "4518656"},
    "Kathleen A. Marchione" => {party: "Republican", conference: "Republican", district: "43", id: "4518861"},
    "Neil Breslin" => {party: "Democratic", conference: "Democratic", district: "44", id: "4518596"},
    "Betty Little" => {party: "Republican", conference: "Republican", district: "45", id: "4518651"},
    "George A. Amedore, Jr." => {party: "Republican", conference: "Republican", district: "46", id: "4518876"},
    "Joseph Griffo" => {party: "Republican", conference: "Republican", district: "47", id: "4518646"},
    "Patty Ritchie" => {party: "Republican", conference: "Republican", district: "48", id: "4518776"},
    "Jim Tedisco" => {party: "Republican", conference: "Republican", district: "49", id: "6253898"},
    "John DeFrancisco" => {party: "Republican", conference: "Republican", district: "50", id: "4518641"},
    "James Seward" => {party: "Republican", conference: "Republican", district: "51", id: "4518636"},
    "Fred Akshar" => {party: "Republican", conference: "Republican", district: "52", id: "6187911"},
    "David Valesky" => {party: "Democratic", conference: "IDC", district: "53", id: "4518616"},
    "Pam Helming" => {party: "Republican", conference: "Republican", district: "54", id: "6253901"},
    "Rich Funke" => {party: "Republican", conference: "Republican", district: "55", id: "4518901"},
    "Joseph Robach" => {party: "Republican", conference: "Republican", district: "56", id: "4518581"},
    "Catharine Young" => {party: "Republican", conference: "Republican", district: "57", id: "4518576"},
    "Tom O'Mara" => {party: "Republican", conference: "Republican", district: "58", id: "4518781"},
    "Patrick Gallivan" => {party: "Republican", conference: "Republican", district: "59", id: "4518786"},
    "Chris Jacobs" => {party: "Republican", conference: "Republican", district: "60", id: "6253903"},
    "Michael H. Ranzenhofer" => {party: "Republican", conference: "Republican", district: "61", id: "4518721"},
    "Robert G. Ortt" => {party: "Republican", conference: "Republican", district: "62", id: "4518906"},
    "Timothy M. Kennedy" => {party: "Democratic", conference: "Democratic", district: "63", id: "4518816"}
  }

  def self.senators_list
    return @senators_list
  end

end
